services:
  - type: web
    name: ai-skin-analyzer-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: cd aurora-main-backend && gunicorn aurora_skin_analyzer.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_PASSWORD
        value: Dante@2025
      - key: DATABASE_HOST
        value: db.ysezicwpvxpyoinljhaf.supabase.co
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ai-skin-analyzer-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-skin-analyzer.vercel.app
      - key: SECRET_KEY
        generateValue: true 