services:
  - type: web
    name: ai-skin-analyzer-backend
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r backend/requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ai-skin-analyzer-nw9c.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-skin-analyzer.vercel.app
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_ROOT
        value: /opt/render/project/src/media
      - key: MEDIA_URL
        value: /media/
      - key: AI_SERVICE_URL
        value: https://us-central1-aurora-457407.cloudfunctions.net/predict
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true

databases:
  - name: ai-skin-analyzer-db
    databaseName: ai_skin_analyzer
    user: ai_skin_analyzer_user
    plan: free 