services:
  - type: web
    name: ai-skin-analyzer-backend
    env: python
    runtime: python3.11
    buildCommand: |
      cd aurora-main-backend
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
      python3 manage.py makemigrations
      python3 manage.py migrate
      python3 manage.py collectstatic --noinput
    startCommand: cd aurora-main-backend && python3 -m gunicorn aurora_skin_analyzer.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    envVars:
      - key: DATABASE_PASSWORD
        value: Dante@2025
      - key: DATABASE_HOST
        value: db.ysezicwpvxpyoinljhaf.supabase.co
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ai-skin-analyzer-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-skin-analyzer.vercel.app
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: aurora_skin_analyzer.settings

databases:
  - name: ai-skin-analyzer-db
    databaseName: ai_skin_analyzer
    user: ai_skin_analyzer_user
    plan: free 