services:
  - type: web
    name: ai-skin-analyzer
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      export DJANGO_SETTINGS_MODULE=backend.settings
      python manage.py migrate
      python backend/create_superuser.py
    startCommand: |
      export DJANGO_SETTINGS_MODULE=backend.settings
      gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin@2024!
    healthCheckPath: /api/ping
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: ai-skin-analyzer-db
    databaseName: ai_skin_analyzer
    user: ai_skin_skin_analyzer_user
    plan: free

  - type: web
    name: ai-skin-analyzer-proxy
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    plan: free
    autoDeploy: true 