services:
  - type: web
    name: ai-skin-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python backend/create_superuser.py
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin@2024!
    healthCheckPath: /api/ping
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: ai-skin-analyzer-db
    databaseName: ai_skin_analyzer
    user: ai_skin_skin_analyzer_user
    plan: free 