services:
  - type: web
    name: ai-skin-analyzer-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      export DJANGO_SETTINGS_MODULE=backend.settings
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        value: django-insecure-BPnp%5x4_b8j9vkWtHh5utiA-T8Fa-OEE8rrJ6wj5WbK#Kx@kS
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ai-skin-analyzer-vmlu.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173,https://ai-skin-analyzer-vmlu.onrender.com
      - key: DATABASE_URL
        value: postgres://postgres:Dante@2025@db.ysezicwpvxpyoinljhaf.supabase.co:5432/
    healthCheckPath: /api/users/token/verify/
    autoDeploy: true
    plan: free

databases:
  - name: ai-skin-analyzer-db
    databaseName: ai_skin_analyzer
    user: ai_skin_analyzer_user
    plan: free 