services:
  - type: web
    name: ai-skin-analyzer-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: ai-skin-analyzer-db
          property: connectionString
    healthCheckPath: /api/users/token/verify/
    autoDeploy: true
    plan: free

databases:
  - name: ai-skin-analyzer-db
    databaseName: postgres
    user: postgres
    plan: free 